title: This is Young Shaw's Home
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yangshaw.github.io" 
site-twitter: #if your site has a twitter account, enter it here


# Author Settings
author: Young Shaw # add your name
author-img: head.jpg # add your photo
about-author: Coder. Student in SDU.
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: YangShaw 
social-linkedin: # add your Linkedin handle
social-email: fuyuxyfy@163.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

excerpt_separator:  '<!-- more -->'

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman
